### ISSUE TITLE
JOSS Review: Contribution/community Guidelines

### ISSUE THREAD

**Issue by emilydolson** [bramvandijk88/cacatoo#15]
According to the JOSS Guidelines:

> There should be clear guidelines for third-parties wishing to:
> 
>     Contribute to the software
>     Report issues or problems with the software
>     Seek support
> 

I'm currently not seeing those. The standard way to create them is to add a file to the top-level of your repo called CONTRIBUTING.md. Github has some nice templates for this that you can access by going to https://github.com/bramvandijk88/cacatoo/community.

(this issue is part of this JOSS review: https://github.com/openjournals/joss-reviews/issues/3948)

**Comment by bramvandijk88** [comment]
On the HTML page on which the Cacatoo models are displayed, there is a footer which states "Issues and suggestions can be reported here", which links to the Github issue page. That said, I agree some notes on this were missing in the repository, and I added a minimal CONTRIBUTING.MD file. 

Thanks for that suggestion, that was totally missing! :)

**Comment by emilydolson** [comment]
Thanks, this looks good!
