### ISSUE TITLE
JOSS Review, some improvements

### ISSUE THREAD

**Issue by TimKam** [bramvandijk88/cacatoo#19]
Hi @bramvandijk88, this issue contains all feedback of my review (https://github.com/openjournals/joss-reviews/issues/3948).

### Installation & Installation Instructions
Typically, one would like to **install** the library by running ``npm install`` or similar.
Even if many in the 'target audience' may prefer working in the HTML files of a copy of the repository, it would be good to document how to work with Cacatoo as a properly managed software artifact that is installed using npm.

Nit-pick: ``npm audit`` finds a low severity vulnerability; of course, in this context the vulnerability is most likely irrelevant.

### Automated tests
To run the tests, one first needs to run ``npm install -g mocha`` or similar, and then ``npm install chai odex``.
Consider managing the dependencies properly in the ``package.json`` file. Also, considering running the tests on a CI like GitHub Actions upon every commit/before every merge.

### Community guidelines
Guidelines "for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support" are missing.

#### Summary
* "is however lagging behind" -> consider removing "however", the contrast is already established by "Despite"
* "limited understanding on how" -> "limited understanding of how"?
* "to make it easy to design," -> "to design," (consider, neutral langauge)
* "Because it requires no installation" is a strong statement, because as a user of the toolbox, one arguably wants to work in the node.js ecosystem.

#### Statement of need
* "are based in C" -> "are written in C" or "require knowledge of C"?
* "and the extensive documentation provides ample opportunity for students and advanced modellers to get started right away!" Consider using neutral language and avoiding exclamation marks.

#### Use Cases
* "The latter model was used in *our* recent work". In the first section, you use "I". Generally, it is good to be consistent, so replace "I" with first person plural ("we").
* "Matthew Fullmer is currently in the process of exploring" -> consider: "Fullmer reports on work in progress that explores..."

**Comment by bramvandijk88** [comment]
Thanks for a the useful feedback. I'll get on it asap. One quick question though: the contribution stuff was also mentioned by the other reviewer. Are you sure I am still missing something? 

Anyway, thanks for all the practical engineering tips. Apposed to you, I am mostly an expert in the biology, and NOT the engineering, so it's very much appreciated!

**Comment by TimKam** [comment]
I suppose there should be a 'Contributing' section or sth. similar in your README or documentation. If you have one, point me to it. (Perhaps I simply failed to find it.)

**Comment by bramvandijk88** [comment]
> I suppose there should be a 'Contributing' section or sth. similar in your README or documentation. If you have one, point me to it. (Perhaps I simply failed to find it.)

There is a CONTRIBUTING.md file. I suppose I could make a reference to that file also in the README.md file. Thanks for clarifying.

**Comment by TimKam** [comment]
This escaped my attention. Thanks, too!

**Comment by bramvandijk88** [comment]
Alright, you can now confirm that I have:

- [x] Published Cacatoo as an npm package (name: cacatoo). I have tested this uploaded package with a few of the provided examples, and everything seems to work as expected.
- [x] Set up a Github Action for unit testing (mocha) upon pull requests. For working on the main branch I prefer to run the tests in my own time (as discussed at an earlier stage of reviews with @bisaloo)
- [x] Considered your paper remarks and made fixes where I agreed. I decided to retain the exclamation mark and other somewhat informal styles, but I have accepted all your other changes as an improvement. 
- [x] Merged CONTRIBUTE.md and README.md into a single file (README.md) so it's harder to overlook (i.e. it's on the main page now)

Once again thank you for your input, I definitely overlooked some things. I am happy with how polished the package has now become! :)

PS I noticed that Github does not automatically index the package as "published". Is there anything I can do to fix that?

**Comment by TimKam** [comment]
For some reason (probably: lack of permissions), I cannot tick the boxes in your comment. Anyway, I think the changes are okay. Regarding GitHub's 'published' information, you need to click the 'Create a new release' link and then tag the commit that reflects the state of the release and enter a description of the release. A minor change you can make is adding the CI status badge to the beginning of the README. You can also try to fix all security vulnerabilities in your npm release, but it's debatable whether what npm/GitHub tags as a 'vulnerability' is relevant in your context. What would be good in the long run (consider opening a new issue for this) is to create an example that demonstrates how to get started with cacatoo in a proper JavaScript project where it is installed via npm (included as a dependency). This could be one of the many examples you have already, merely with a slightly different setup.

**Comment by bramvandijk88** [comment]
> What would be good in the long run (consider opening a new issue for this) is to create an example that demonstrates how to get started with cacatoo in a proper JavaScript project where it is installed via npm (included as a dependency). This could be one of the many examples you have already, merely with a slightly different setup.

Absolutely. I'm also working on serialisation options for the future, which is especially useful for projects that are ran from the command line :)
