### ISSUE TITLE
GoL runs too fast to see anything

### ISSUE THREAD

**Issue by meijer-jeroen** [bramvandijk88/cacatoo#7]
The GoL tutorial now runs way too fast. Various dynamic patterns move too fast to see individual steps -- instead, you see a blurred average (i.e. blinkers appear as a cross to the observer, with the center square a brighter white than the other gridpoints). This obfuscates key elements the tutorial tries to teach, such as the next state function and that each gridpoint only has 2 possible states (0 and 1).    

One solution would be to add sleep = 100 to the config. Alternatively, it would be really useful for students could use a slider to manipulate sleep, giving them control over the speed of the simulation and allowing them to explore the simulation.

**Comment by bramvandijk88** [comment]
Solved by adding a new type of slider with function "addCustomSlider" (commit #86b8e406610e895f0c8b8031f254f5691f59a573). This function allows users to add a custom callback-function to their slider, which will use the value of the input-element as its argument.
